INSERT INTO shelters (username, password, name, address, city, state, postcode, phone_number, email, logo, description) 
VALUES ('shelter1', 'helloShelter1', 'Grand County Animal Shelter and Animal Control', 
'3475 CR 57', 'Granby', 'CO', '80446', '(970) 887-2988', 'N/A', 
'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/organization-photos\/28165\/1\/?bust=1514940142&width=100', null),
('shelter2', 'helloShelter2', 'Happy Landings Animal Rescue', 
'N/A', 'Fort Collins', 'CO', '80525', '(214) 771-2475', 'happylandingsrescue@yahoo.com', 
'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/organization-photos\/44144\/2\/?bust=1511942613&width=100', 
'Happy Landings Animal Rescue is an animal rescue group operating in TX and WY. We have rescued many animals from...'),
('shelter3', 'helloShelter3', 'Beagles of New England States Inc. (B.O.N.E.S.), Inc.', 
'PO Box 1510', 'New Boston', 'NH', '03070', '(508) 473-2228', 'adoptions@bonesbeagles.org', 
'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/organization-photos\/33808\/1\/?bust=1511963387&width=100', 
'N/A');

INSERT INTO breed (id, breed)
VALUES (1, 'Affenpinscher'),
(2, 'Afghan Hound'),
(3, 'Airedale Terrier'),
(4, 'Akbash'),
(5, 'Akita'),
(6, 'Alaskan Malamute'),
(7, 'American Bulldog'),
(8, 'American Bully'),
(9, 'American Eskimo Dog'),
(10, 'American Foxhound'),
(11, 'American Hairless Terrier'),
(12, 'American Staffordshire Terrier'),
(13, 'American Water Spaniel'),
(14, 'Anatolian Shepherd'),
(15, 'Appenzell Mountain Dog'),
(16, 'Aussiedoodle'),
(17, 'Australian Cattle Dog / Blue Heeler'),
(18, 'Australian Kelpie'),
(19, 'Australian Shepherd'),
(20, 'Australian Terrier'),
(21, 'Basenji'),
(22, 'Basset Hound'),
(23, 'Beagle'),
(24, 'Bearded Collie'),
(25, 'Beauceron'),
(26, 'Bedlington Terrier'),
(27, 'Belgian Shepherd / Laekenois'),
(28, 'Belgian Shepherd / Malinois'),
(29, 'Belgian Shepherd / Sheepdog'),
(30, 'Belgian Shepherd / Tervuren'),
(31, 'Bernedoodle'),
(32, 'Bernese Mountain Dog'),
(33, 'Bichon Frise'),
(34, 'Black and Tan Coonhound'),
(35, 'Black Labrador Retriever'),
(36, 'Black Mouth Cur'),
(37, 'Black Russian Terrier'),
(38, 'Bloodhound'),
(39, 'Blue Lacy'),
(40, 'Bluetick Coonhound'),
(41, 'Boerboel'),
(42, 'Bolognese'),
(43, 'Border Collie'),
(44, 'Border Terrier'),
(45, 'Borzoi'),
(46, 'Boston Terrier'),
(47, 'Bouvier des Flandres'),
(48, 'Boxer'),
(49, 'Boykin Spaniel'),
(50, 'Briard'),
(51, 'Brittany Spaniel'),
(52, 'Brussels Griffon'),
(53, 'Bull Terrier'),
(54, 'Bullmastiff'),
(55, 'Cairn Terrier'),
(56, 'Canaan Dog'),
(57, 'Cane Corso'),
(58, 'Cardigan Welsh Corgi'),
(59, 'Carolina Dog'),
(60, 'Catahoula Leopard Dog'),
(61, 'Cattle Dog'),
(62, 'Caucasian Sheepdog / Caucasian Ovtcharka'),
(63, 'Cavachon'),
(64, 'Cavalier King Charles Spaniel'),
(65, 'Cavapoo'),
(66, 'Chesapeake Bay Retriever'),
(67, 'Chihuahua'),
(68, 'Chinese Crested Dog'),
(69, 'Chinese Foo Dog'),
(70, 'Chinook'),
(71, 'Chiweenie'),
(72, 'Chocolate Labrador Retriever'),
(73, 'Chow Chow'),
(74, 'Cirneco dell Etna'),
(75, 'Clumber Spaniel'),
(76, 'Cockapoo'),
(77, 'Cocker Spaniel'),
(78, 'Collie'),
(79, 'Coonhound'),
(80, 'Corgi'),
(81, 'Coton de Tulear'),
(82, 'Curly-Coated Retriever'),
(83, 'Dachshund'),
(84, 'Dalmatian'),
(85, 'Dandie Dinmont Terrier'),
(86, 'Doberman Pinscher'),
(87, 'Dogo Argentino'),
(88, 'Dogue de Bordeaux'),
(89, 'Dutch Shepherd'),
(90, 'English Bulldog'),
(91, 'English Cocker Spaniel'),
(92, 'English Coonhound'),
(93, 'English Foxhound'),
(94, 'English Pointer'),
(95, 'English Setter'),
(96, 'English Shepherd'),
(97, 'English Springer Spaniel'),
(98, 'English Toy Spaniel'),
(99, 'Entlebucher'),
(100, 'Eskimo Dog'),
(101, 'Feist'),
(102, 'Field Spaniel'),
(103, 'Fila Brasileiro'),
(104, 'Finnish Lapphund'),
(105, 'Finnish Spitz'),
(106, 'Flat-Coated Retriever'),
(107, 'Fox Terrier'),
(108, 'Foxhound'),
(109, 'French Bulldog'),
(110, 'Galgo Spanish Greyhound'),
(111, 'German Pinscher'),
(112, 'German Shepherd Dog'),
(113, 'German Shorthaired Pointer'),
(114, 'German Spitz'),
(115, 'German Wirehaired Pointer'),
(116, 'Giant Schnauzer'),
(117, 'Glen of Imaal Terrier'),
(118, 'Golden Retriever'),
(119, 'Goldendoodle'),
(120, 'Gordon Setter'),
(121, 'Great Dane'),
(122, 'Great Pyrenees'),
(123, 'Greater Swiss Mountain Dog'),
(124, 'Greyhound'),
(125, 'Hamiltonstovare'),
(126, 'Harrier'),
(127, 'Havanese'),
(128, 'Hound'),
(129, 'Hovawart'),
(130, 'Husky'),
(131, 'Ibizan Hound'),
(132, 'Icelandic Sheepdog'),
(133, 'Illyrian Sheepdog'),
(134, 'Irish Setter'),
(135, 'Irish Terrier'),
(136, 'Irish Water Spaniel'),
(137, 'Irish Wolfhound'),
(138, 'Italian Greyhound'),
(139, 'Jack Russell Terrier'),
(140, 'Japanese Chin'),
(141, 'Jindo'),
(142, 'Kai Dog'),
(143, 'Karelian Bear Dog'),
(144, 'Keeshond'),
(145, 'Kerry Blue Terrier'),
(146, 'Kishu'),
(147, 'Klee Kai'),
(148, 'Komondor'),
(149, 'Kuvasz'),
(150, 'Kyi Leo'),
(151, 'Labradoodle'),
(152, 'Labrador Retriever'),
(153, 'Lakeland Terrier'),
(154, 'Lancashire Heeler'),
(155, 'Leonberger'),
(156, 'Lhasa Apso'),
(157, 'Lowchen'),
(158, 'Lurcher'),
(159, 'Maltese'),
(160, 'Maltipoo'),
(161, 'Manchester Terrier'),
(162, 'Maremma Sheepdog'),
(163, 'Mastiff'),
(164, 'McNab'),
(165, 'Miniature Bull Terrier'),
(166, 'Miniature Dachshund'),
(167, 'Miniature Pinscher'),
(168, 'Miniature Poodle'),
(169, 'Miniature Schnauzer'),
(170, 'Mixed Breed'),
(171, 'Morkie'),
(172, 'Mountain Cur'),
(173, 'Mountain Dog'),
(174, 'Munsterlander'),
(175, 'Neapolitan Mastiff'),
(176, 'New Guinea Singing Dog'),
(177, 'Newfoundland Dog'),
(178, 'Norfolk Terrier'),
(179, 'Norwegian Buhund'),
(180, 'Norwegian Elkhound'),
(181, 'Norwegian Lundehund'),
(182, 'Norwich Terrier'),
(183, 'Nova Scotia Duck Tolling Retriever'),
(184, 'Old English Sheepdog'),
(185, 'Otterhound'),
(186, 'Papillon'),
(187, 'Parson Russell Terrier'),
(188, 'Patterdale Terrier / Fell Terrier'),
(189, 'Pekingese'),
(190, 'Pembroke Welsh Corgi'),
(191, 'Peruvian Inca Orchid'),
(192, 'Petit Basset Griffon Vendeen'),
(193, 'Pharaoh Hound'),
(194, 'Pit Bull Terrier'),
(195, 'Plott Hound'),
(196, 'Pointer'),
(197, 'Polish Lowland Sheepdog'),
(198, 'Pomeranian'),
(199, 'Pomsky'),
(200, 'Poodle'),
(201, 'Portuguese Podengo'),
(202, 'Portuguese Water Dog'),
(203, 'Presa Canario'),
(204, 'Pug'),
(205, 'Puggle'),
(206, 'Puli'),
(207, 'Pumi'),
(208, 'Pyrenean Shepherd'),
(209, 'Rat Terrier'),
(210, 'Redbone Coonhound'),
(211, 'Retriever'),
(212, 'Rhodesian Ridgeback'),
(213, 'Rottweiler'),
(214, 'Rough Collie'),
(215, 'Saint Bernard'),
(216, 'Saluki'),
(217, 'Samoyed'),
(218, 'Sarplaninac'),
(219, 'Schipperke'),
(220, 'Schnauzer'),
(221, 'Schnoodle'),
(222, 'Scottish Deerhound'),
(223, 'Scottish Terrier'),
(224, 'Sealyham Terrier'),
(225, 'Setter'),
(226, 'Shar-Pei'),
(227, 'Sheep Dog'),
(228, 'Sheepadoodle'),
(229, 'Shepherd'),
(230, 'Shetland Sheepdog / Sheltie'),
(231, 'Shiba Inu'),
(232, 'Shih poo'),
(233, 'Shih Tzu'),
(234, 'Shollie'),
(235, 'Siberian Husky'),
(236, 'Silky Terrier'),
(237, 'Skye Terrier'),
(238, 'Sloughi'),
(239, 'Smooth Collie'),
(240, 'Smooth Fox Terrier'),
(241, 'South Russian Ovtcharka'),
(242, 'Spaniel'),
(243, 'Spanish Water Dog'),
(244, 'Spinone Italiano'),
(245, 'Spitz'),
(246, 'Staffordshire Bull Terrier'),
(247, 'Standard Poodle'),
(248, 'Standard Schnauzer'),
(249, 'Sussex Spaniel'),
(250, 'Swedish Vallhund'),
(251, 'Tennessee Treeing Brindle'),
(252, 'Terrier'),
(253, 'Thai Ridgeback'),
(254, 'Tibetan Mastiff'),
(255, 'Tibetan Spaniel'),
(256, 'Tibetan Terrier'),
(257, 'Tosa Inu'),
(258, 'Toy Fox Terrier'),
(259, 'Toy Manchester Terrier'),
(260, 'Treeing Walker Coonhound'),
(261, 'Vizsla'),
(262, 'Weimaraner'),
(263, 'Welsh Springer Spaniel'),
(264, 'Welsh Terrier'),
(265, 'West Highland White Terrier / Westie'),
(266, 'Wheaten Terrier'),
(267, 'Whippet'),
(268, 'White German Shepherd'),
(269, 'Wire Fox Terrier'),
(270, 'Wirehaired Dachshund'),
(271, 'Wirehaired Pointing Griffon'),
(272, 'Wirehaired Terrier'),
(273, 'Xoloitzcuintli / Mexican Hairless'),
(274, 'Yellow Labrador Retriever'),
(275, 'Yorkshire Terrier');

INSERT INTO adoptable_dogs (name, breed_id, gender, age, picture, description, days_at_shelter, good_w_kids, good_w_dogs, good_w_cats, shelter_id)
VALUES ('Choco', 130, 'Male', 'Young', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55194486\/1\/?bust=1648996693&width=100', 
'Hi there!!  My name is Choco and I am a 1 year old, Husky X.  I am already a big...', null, true, true, null, 1),
('Blue', 43, 'Female', 'Young', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55002797\/1\/?bust=1647468675&width=100', 
'My name is Blue and I am looking for a home where I can be the only dog.  I am...', null, null, null, null, 1),
('Mocha', 252, 'Male', 'Young', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/54511989\/1\/?bust=1643991592&width=100', 
'This is Mocha.  He is about an 8 month old, Terrier cross.  Mocha, like his siblings Titi and Lita, have...', null, null, true, null, 1),
('Marshmallow', 229, 'Female', 'Baby', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55005777\/1\/?bust=1647481481&width=100', 
'Say hello to Marshmallow! This sweet girl was born in our rescue after her mother was surrendered as a stray....', null, true, true, null, 2),
('German Shepherd Mix PUPPIES!!!', 112, 'Female', 'Baby', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55005728\/1\/?bust=1647480729&width=100', 
'Our rescue was alerted to a sweet, young, female German Shepherd that was lying on the side of a county...', null, true, true, true, 2),
('German Shepherd Mix PUPPIES!!!', 112, 'Male', 'Baby', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55005722\/1\/?bust=1647480499&width=100', 
'Our rescue was alerted to a sweet, young, female German Shepherd that was lying on the side of a county...', null, true, true, true, 2),
('Chief', 28, 'Male', 'Adult', 'https://thumbs.dreamstime.com/z/avatar-dog-avatar-dog-white-background-vector-illustration-105121614.jpg', 
null, null, null, null, null, 3),
('Hope', 128, 'Female', 'Adult', 'https://thumbs.dreamstime.com/z/avatar-dog-avatar-dog-white-background-vector-illustration-105121614.jpg', 
null, null, null, null, null, 3),
('Alfie', 23, 'Male', 'Young', 'https:\/\/dl5zpyw5k3jeb.cloudfront.net\/photos\/pets\/55367212\/1\/?bust=1650641371&width=100', 
'Meet Alfie! Alfie is a 28 lb, one year old Beagle found as a stray in a creek. He has...', null, null, true, null, 3);

INSERT INTO adopters (username, password, email, description, private_outdoors, num_of_dogs, preferred_gender, preferred_age)
VALUES ('nhawker0', 'yrnwI0KK', 'hfjuhb@gmail.com','morph revolutionary niches', false, 1, 'Female', 'Young'),
('fwadlow1', '60eForkV', 'bfjhbu@hotmail.com', 'recontextualize user-centric convergence', false, 2, 'Female', 'Baby'),
('cbein2', 'XT1X8Ox', 'bfghui@yahoo.com', 'visualize vertical eyeballs', false, 3, 'Female', 'Adult');

